version: "3"

services:
    https-portal:
        container_name: "https-portal"
        image: "steveltn/https-portal:1"
        ports:
          - "80:80"
          - "443:443"
        links:
          - "api"
          - "mongo-express"
        restart: "always"
        environment:
            DOMAINS: "yurararan.nothink.jp -> http://api:1323, mongo.nothink.jp -> http://mongo-express:8081"
            STAGE: "production"
#            FORCE_RENEW: true
        volumes:
          - "/var/www/certs:/var/lib/https-portal"

    api:
        container_name: "yurararan"
        build: "src/"
        ports:
          - "1323:1323"
        restart: "always"
        env_file:
          - "api.env"
        volumes:
          - "/var/www/verenav:/verenav"

    mongo:
        container_name: "mongo"
        image: "mongo:latest"
        restart: "always"
        env_file:
          - "mongo.env"
        volumes:
          - "/var/db/mongo:/data/db"

    mongo-express:
        container_name: "mongo-express"
        image: "mongo-express:latest"
        ports:
          - "8081:8081"
        restart: "always"
        links:
          - "mongo"
        env_file:
          - "mongo-express.env"
