version: "3"

services:
    https-portal:
        container_name: https-portal
        image: steveltn/https-portal:1
        ports:
          - '80:80'
          - '443:443'
        links:
          - api
        restart: always
        environment:
            DOMAINS: 'yurararan.nothink.jp -> http://api:1323'
            STAGE: 'production'
#            FORCE_RENEW: 'true'
        volumes:
          - /var/www/certs:/var/lib/https-portal

    api:
        container_name: yurararan
        build: src/
        ports:
          - 1323:1323
        restart: always
        env_file:
          - api.env
        volumes:
          - /var/www/verenav:/verenav
